stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace ProjectName.xcodeproj -scheme SchemeName | xcpretty
    - xcodebuild test -workspace ProjectName.xcodeproj -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' | xcpretty -s
  tags:
    - ios_9-2
    - xcode_7-2
    - osx_10-11
