stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace TomatoCrypto.xcworkspace -scheme 'TomatoCrypto-OSX' | xcpretty
    - xcodebuild test -workspace TomatoCrypto.xcworkspace -scheme 'TomatoCrypto-OSX' -destination 'platform=OS X,arch=x86_64' | xcpretty -s
  tags:
    - osx_10-12
    - xcode_8-1
